# Generated by Django 3.2.5 on 2021-07-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_collection_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.collection'),
        ),
    ]
